import Script from "next/script"
import Link from "next/link"
import { HeaderEs } from "@/components/header-es"
import { FooterEs } from "@/components/footer-es"
import { TranslatePdfInterface } from "@/components/translate-pdf-interface"
import { Languages, Zap, Shield } from "lucide-react"

export const metadata = {
  title: "Traducir PDF — Traducción de Documentos con IA a 13 Idiomas | PDF.it",
  description: "Sube cualquier PDF y tradúcelo a inglés, español, portugués, francés, alemán, italiano, chino, japonés, coreano, árabe, ruso, hindi u holandés. Traducción con IA para contratos, reportes y documentos. Función del plan Business.",
  alternates: { canonical: "https://pdf.it.com/es/traducir-pdf", languages: { "en": "https://pdf.it.com/translate-pdf", "es": "https://pdf.it.com/es/traducir-pdf", "pt-BR": "https://pdf.it.com/br/traduzir-pdf" } },
}
const faqs = [
  { q: "¿Qué es Traducir PDF?", a: "Traducir PDF usa IA para traducir el contenido completo de cualquier documento PDF al idioma que elijas. Soporta 13 idiomas incluyendo inglés, español, portugués, francés, alemán, chino, japonés y más." },
  { q: "¿Qué idiomas soporta?", a: "Inglés, español, portugués brasileño, francés, alemán, italiano, holandés, chino simplificado, japonés, coreano, árabe, ruso e hindi." },
  { q: "¿Preserva el diseño del PDF original?", a: "El texto traducido se entrega como texto legible que preserva la estructura de párrafos y los saltos de sección. Para traducción con diseño exacto, recomendamos copiar el texto traducido en tu plantilla de documento original." },
  { q: "¿Qué tan precisa es la traducción?", a: "Las traducciones usan GPT-4o-mini que proporciona traducciones de calidad profesional. Maneja bien documentos comerciales, legales y técnicos. Para traducciones certificadas, siempre haz que un traductor humano revise el resultado." },
  { q: "¿Qué plan necesito?", a: "Traducir PDF es una función del plan Business a $13.99/mes. Incluye todas las demás herramientas Business como Chat con PDF, Extracción Inteligente, Resumidor y más." },
  { q: "¿Puedo descargar la traducción?", a: "Sí. Puedes copiar la traducción al portapapeles o descargarla como archivo de texto con un clic." },
]
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map((faq) => ({ "@type": "Question", "name": faq.q, "acceptedAnswer": { "@type": "Answer", "text": faq.a } })) }

export default function TraducirPdfPage() {
  return (
    <div className="min-h-screen bg-[#F3F4FF]">
      <HeaderEs />
      <main>
        <section className="text-white py-16 relative overflow-hidden" style={{ background: `radial-gradient(ellipse 70% 50% at 50% 0%, rgba(20,216,196,0.15) 0%, transparent 60%), radial-gradient(ellipse 50% 40% at 80% 70%, rgba(232,129,58,0.06) 0%, transparent 50%), radial-gradient(ellipse 60% 60% at 15% 80%, rgba(107,124,255,0.10) 0%, transparent 60%), #0E0F1E` }}>
          <svg className="absolute inset-0 w-full h-full pointer-events-none" style={{ opacity: 0.04 }}><filter id="heroGrain"><feTurbulence type="fractalNoise" baseFrequency="0.65" numOctaves="3" stitchTiles="stitch" /></filter><rect width="100%" height="100%" filter="url(#heroGrain)" /></svg>
          <div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10"><div className="max-w-4xl mx-auto text-center">
            <div className="w-20 h-20 rounded-2xl flex items-center justify-center mx-auto mb-6" style={{ background: "linear-gradient(135deg, #1a1f5e, #252A6A)", boxShadow: "0 0 30px rgba(20, 216, 196, 0.35), 0 4px 12px rgba(232,129,58,0.1)" }}><Languages className="h-10 w-10 text-[#14D8C4]" /></div>
            <h1 className="text-4xl lg:text-5xl font-black mb-4">Traducir PDF</h1>
            <p className="text-xl text-slate-300 mb-8">Sube cualquier PDF y tradúcelo a 13 idiomas con IA. Traducción de calidad profesional para contratos, reportes y documentos.</p>
            <div className="flex flex-wrap justify-center gap-6 mb-8 text-sm font-semibold"><div className="flex items-center gap-2"><Languages className="h-4 w-4 text-[#14D8C4]" /><span>13 Idiomas</span></div><div className="flex items-center gap-2"><Zap className="h-4 w-4 text-[#14D8C4]" /><span>Impulsado por IA</span></div><div className="flex items-center gap-2"><Shield className="h-4 w-4 text-[#14D8C4]" /><span>Seguro y Privado</span></div></div>
          </div></div>
        </section>
        <section className="py-10 bg-[#F3F4FF]"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-3xl text-center"><p className="text-lg text-slate-600 leading-relaxed">¿Necesitas entender un documento en otro idioma? Sube tu PDF y nuestra IA lo traduce al idioma que elijas — preservando la estructura del documento, los nombres propios y el tono profesional. Soporta 13 idiomas incluyendo inglés, español, francés, alemán, chino y más.</p><ul className="mt-6 grid grid-cols-1 sm:grid-cols-2 gap-3 text-left text-slate-700 text-sm font-medium"><li className="flex items-center gap-2">✓ 13 idiomas soportados</li><li className="flex items-center gap-2">✓ Traducción profesional con IA</li><li className="flex items-center gap-2">✓ Preserva la estructura del documento</li><li className="flex items-center gap-2">✓ Copia o descarga la traducción</li></ul></div></section>
        <TranslatePdfInterface />
        <section className="py-16" style={{ background: `radial-gradient(ellipse 60% 40% at 50% 0%, rgba(20,216,196,0.04) 0%, transparent 50%), radial-gradient(ellipse 50% 50% at 100% 80%, rgba(232,129,58,0.03) 0%, transparent 50%), #0E0F1E` }}><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl"><div className="grid grid-cols-1 md:grid-cols-3 gap-4">{[{ title: "Contratos y Documentos Legales", desc: "Traduce contratos, acuerdos y documentos legales preservando términos clave, nombres de partes y estructura de cláusulas." },{ title: "Reportes y Correspondencia", desc: "Traduce reportes financieros, propuestas comerciales y correspondencia internacional al idioma de tu equipo." },{ title: "Documentos Académicos", desc: "Accede a investigaciones publicadas en otros idiomas. Traduce artículos académicos, estudios y publicaciones." }].map((f) => (<div key={f.title} className="rounded-xl p-[1px]" style={{ background: "linear-gradient(135deg, rgba(20,216,196,0.4), rgba(107,124,255,0.2), rgba(232,129,58,0.25), rgba(20,216,196,0.1))" }}><div className="rounded-[11px] p-6 h-full" style={{ background: `radial-gradient(ellipse 70% 60% at 95% 90%, rgba(232,129,58,0.06) 0%, transparent 70%), radial-gradient(ellipse 50% 50% at 5% 10%, rgba(20,216,196,0.04) 0%, transparent 60%), rgba(255, 255, 255, 0.07)`, backdropFilter: "blur(12px)", WebkitBackdropFilter: "blur(12px)", boxShadow: "inset 0 -1px 1px rgba(232,129,58,0.08), 0 2px 8px rgba(0,0,0,0.3)" }}><h3 className="text-lg font-bold text-white mb-2">{f.title}</h3><p className="text-slate-400 text-sm leading-relaxed">{f.desc}</p></div></div>))}</div></div></section>
        <section className="py-16 bg-[#F3F4FF]"><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-3xl"><h2 className="text-3xl font-black text-slate-900 mb-8 text-center">Cómo Traducir un PDF</h2><div className="flex flex-col sm:flex-row gap-6 justify-center text-center">{[{ num: "1", title: "Sube tu PDF", desc: "Arrastra y suelta o haz clic" },{ num: "2", title: "Elige idioma", desc: "Selecciona entre 13 idiomas" },{ num: "3", title: "Obtén la traducción", desc: "Copia o descarga el resultado" }].map((s) => (<div key={s.num} className="flex-1"><div className="w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-3" style={{ background: "linear-gradient(135deg, #1a1f5e, #252A6A)", boxShadow: "0 0 20px rgba(20, 216, 196, 0.3), 0 4px 8px rgba(232,129,58,0.1)", border: "1px solid rgba(20,216,196,0.25)" }}><span className="text-[#14D8C4] font-black text-lg">{s.num}</span></div><p className="font-semibold text-slate-900">{s.title}</p><p className="text-sm text-slate-500 mt-1">{s.desc}</p></div>))}</div></div></section>
        <section className="py-16" style={{ background: "#0E0F1E" }}><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl"><h2 className="text-2xl font-black text-white mb-6 text-center">Herramientas Relacionadas</h2><div className="grid grid-cols-2 sm:grid-cols-4 gap-4">{[{ name: "Resumidor de PDF", href: "/es/resumidor-pdf", desc: "Resumir en cualquier idioma" },{ name: "Chat con PDF", href: "/es/chat-con-pdf", desc: "Preguntas sobre PDFs" },{ name: "PDF a Texto", href: "/es/pdf-a-texto", desc: "Extraer texto" },{ name: "Escáner OCR", href: "/es/escaner-ocr", desc: "Hacer PDFs buscables" }].map((t) => (<div key={t.href} className="rounded-xl p-[1px]" style={{ background: "linear-gradient(135deg, rgba(20,216,196,0.4), rgba(107,124,255,0.2), rgba(232,129,58,0.25), rgba(20,216,196,0.1))" }}><Link href={t.href} className="rounded-[11px] p-4 transition-all duration-200 hover:-translate-y-1 block h-full text-center flex flex-col justify-center min-h-[80px]" style={{ background: `radial-gradient(ellipse 70% 60% at 95% 90%, rgba(232,129,58,0.06) 0%, transparent 70%), radial-gradient(ellipse 50% 50% at 5% 10%, rgba(20,216,196,0.04) 0%, transparent 60%), rgba(255, 255, 255, 0.07)`, backdropFilter: "blur(12px)", WebkitBackdropFilter: "blur(12px)", boxShadow: "inset 0 -1px 1px rgba(232,129,58,0.08), 0 2px 8px rgba(0,0,0,0.3)" }}><div className="font-bold text-[#14D8C4] text-sm mb-1">{t.name}</div><div className="text-xs text-slate-400">{t.desc}</div></Link></div>))}</div></div></section>
        <section className="py-16" style={{ background: `radial-gradient(ellipse 70% 40% at 30% 20%, rgba(232,129,58,0.07) 0%, transparent 55%), radial-gradient(ellipse 60% 50% at 80% 80%, rgba(20,216,196,0.06) 0%, transparent 55%), radial-gradient(ellipse 50% 40% at 60% 0%, rgba(107,124,255,0.05) 0%, transparent 50%), radial-gradient(ellipse 40% 30% at 10% 70%, rgba(232,129,58,0.04) 0%, transparent 50%), #0E0F1E` }}><div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-3xl"><h2 className="text-3xl font-black text-white mb-10 text-center">Preguntas Frecuentes</h2><div className="space-y-4">{faqs.map((faq, i) => (<div key={i} className="rounded-xl p-6" style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)", boxShadow: "0 2px 8px rgba(0,0,0,0.1)" }}><h3 className="text-lg font-bold text-white mb-2">{faq.q}</h3><p className="text-slate-300 leading-relaxed text-sm">{faq.a}</p></div>))}</div></div></section>
        <Script id="faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      </main>
      <FooterEs />
    </div>
  )
}
