"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import * as Diff from "diff"
import { PDFDocument, StandardFonts, rgb } from "pdf-lib"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import {
  ArrowLeftRight,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  Crown,
  Download,
  FileText,
  Loader2,
  Upload,
  X,
} from "lucide-react"
import { cn } from "@/lib/utils"
import { TrustBadges } from "@/components/trust-badges"

type ToolLocale = "en" | "es" | "br"

const PDF_COMPARE_COPY = {
  en: {
    signupPath: "/signup-required",
    pricingPath: "/pricing",
    pricingSourcePath: "/pricing?source=pdf-compare",
    loading: "Loading PDF Compare...",
    businessFeature: "Business Feature",
    businessDescription: "PDF Compare is available on the Business plan. Upload two PDFs and review word-level edits side by side.",
    upgradeButton: "Upgrade to Business — $13.99/mo",
    upgradeTitle: "This Feature Requires an Upgrade",
    limitTitle: "You're out of free conversions",
    upgradeLabel: "Upgrade to Business",
    upgradeDescription: "This tool is available on the Business plan. Upgrade to unlock unlimited access to all PDF tools.",
    limitDescription: "Free includes 10 conversions per day. Upgrade for unlimited conversions.",
    goBack: "Go Back",
    invalidPdf: "Please upload a valid PDF file.",
    originalPdfEmpty: "The original PDF has no readable pages.",
    modifiedPdfEmpty: "The modified PDF has no readable pages.",
    originalPdfReadFailed: "Failed to read the original PDF.",
    modifiedPdfReadFailed: "Failed to read the modified PDF.",
    identical: "Identical",
    minorChanges: "Minor changes",
    moderateChanges: "Moderate changes",
    majorChanges: "Major changes",
    reportTitle: "PDF COMPARISON REPORT",
    reportGeneratedBy: "Generated by PDF.it",
    reportStatus: "Status",
    reportAdded: "Added",
    reportRemoved: "Removed",
    reportTotal: "Total",
    reportPage: "Page",
    reportDetailedChanges: "Detailed Changes",
    reportContinued: "continued",
    reportChange: "Change",
    reportRemovedLabel: "REMOVED",
    reportAddedLabel: "ADDED",
    reportGenerationFailed: "Failed to generate the comparison report. Please try again.",
    reportFileName: "PDF-Comparison-Report.pdf",
    originalPdf: "Original PDF",
    modifiedPdf: "Modified PDF",
    extractingText: "Extracting text...",
    remove: "Remove",
    uploadOriginalPdf: "Upload original PDF",
    uploadModifiedPdf: "Upload modified PDF",
    dragAndDrop: "Drag and drop or click to browse",
    generating: "Generating...",
    report: "Report",
    newCompare: "New Compare",
    pageOf: "Page {current} of {total}",
    removedWords: "Removed words",
    addedWords: "Added words",
    original: "Original",
    modified: "Modified",
    noTextContent: "No text content on this page.",
    pageSummary: "Page Summary",
    same: "Same",
    word: "word",
    words: "words",
    pageSingular: "page",
    pagePlural: "pages",
  },
  es: {
    signupPath: "/es/registro-requerido",
    pricingPath: "/es/precios",
    pricingSourcePath: "/es/precios?source=pdf-compare",
    loading: "Cargando Comparar PDF...",
    businessFeature: "Función Business",
    businessDescription: "Comparar PDF está disponible en el plan Business. Sube dos PDFs y revisa cambios palabra por palabra lado a lado.",
    upgradeButton: "Mejorar a Business — $13.99/mes",
    upgradeTitle: "Esta función requiere una mejora",
    limitTitle: "Ya no tienes conversiones gratis",
    upgradeLabel: "Mejorar a Business",
    upgradeDescription: "Esta herramienta está disponible en el plan Business. Mejora para desbloquear acceso ilimitado a todas las herramientas PDF.",
    limitDescription: "Free incluye 10 conversiones por día. Mejora para conversiones ilimitadas.",
    goBack: "Volver",
    invalidPdf: "Por favor, sube un archivo PDF válido.",
    originalPdfEmpty: "El PDF original no tiene páginas legibles.",
    modifiedPdfEmpty: "El PDF modificado no tiene páginas legibles.",
    originalPdfReadFailed: "No se pudo leer el PDF original.",
    modifiedPdfReadFailed: "No se pudo leer el PDF modificado.",
    identical: "Idéntico",
    minorChanges: "Cambios menores",
    moderateChanges: "Cambios moderados",
    majorChanges: "Cambios mayores",
    reportTitle: "REPORTE DE COMPARACION DE PDF",
    reportGeneratedBy: "Generado por PDF.it",
    reportStatus: "Estado",
    reportAdded: "Agregado",
    reportRemoved: "Eliminado",
    reportTotal: "Total",
    reportPage: "Página",
    reportDetailedChanges: "Cambios detallados",
    reportContinued: "continuación",
    reportChange: "Cambio",
    reportRemovedLabel: "ELIMINADO",
    reportAddedLabel: "AGREGADO",
    reportGenerationFailed: "No se pudo generar el reporte de comparación. Inténtalo de nuevo.",
    reportFileName: "Reporte-Comparacion-PDF.pdf",
    originalPdf: "PDF original",
    modifiedPdf: "PDF modificado",
    extractingText: "Extrayendo texto...",
    remove: "Eliminar",
    uploadOriginalPdf: "Subir PDF original",
    uploadModifiedPdf: "Subir PDF modificado",
    dragAndDrop: "Arrastra y suelta o haz clic para explorar",
    generating: "Generando...",
    report: "Reporte",
    newCompare: "Nueva comparación",
    pageOf: "Página {current} de {total}",
    removedWords: "Palabras eliminadas",
    addedWords: "Palabras agregadas",
    original: "Original",
    modified: "Modificado",
    noTextContent: "No hay contenido de texto en esta página.",
    pageSummary: "Resumen por página",
    same: "Igual",
    word: "palabra",
    words: "palabras",
    pageSingular: "página",
    pagePlural: "páginas",
  },
  br: {
    signupPath: "/br/cadastro-obrigatorio",
    pricingPath: "/br/precos",
    pricingSourcePath: "/br/precos?source=pdf-compare",
    loading: "Carregando Comparar PDF...",
    businessFeature: "Recurso Business",
    businessDescription: "Comparar PDF está disponível no plano Business. Envie dois PDFs e revise alterações palavra por palavra lado a lado.",
    upgradeButton: "Fazer upgrade para Business — $13.99/mês",
    upgradeTitle: "Este recurso exige upgrade",
    limitTitle: "Você ficou sem conversões gratuitas",
    upgradeLabel: "Fazer upgrade para Business",
    upgradeDescription: "Esta ferramenta está disponível no plano Business. Faça upgrade para desbloquear acesso ilimitado a todas as ferramentas PDF.",
    limitDescription: "Free inclui 10 conversões por dia. Faça upgrade para conversões ilimitadas.",
    goBack: "Voltar",
    invalidPdf: "Envie um arquivo PDF válido.",
    originalPdfEmpty: "O PDF original não tem páginas legíveis.",
    modifiedPdfEmpty: "O PDF modificado não tem páginas legíveis.",
    originalPdfReadFailed: "Falha ao ler o PDF original.",
    modifiedPdfReadFailed: "Falha ao ler o PDF modificado.",
    identical: "Idêntico",
    minorChanges: "Mudanças menores",
    moderateChanges: "Mudanças moderadas",
    majorChanges: "Mudanças maiores",
    reportTitle: "RELATORIO DE COMPARACAO DE PDF",
    reportGeneratedBy: "Gerado por PDF.it",
    reportStatus: "Status",
    reportAdded: "Adicionado",
    reportRemoved: "Removido",
    reportTotal: "Total",
    reportPage: "Página",
    reportDetailedChanges: "Mudanças detalhadas",
    reportContinued: "continuação",
    reportChange: "Mudança",
    reportRemovedLabel: "REMOVIDO",
    reportAddedLabel: "ADICIONADO",
    reportGenerationFailed: "Falha ao gerar o relatório de comparação. Tente novamente.",
    reportFileName: "Relatorio-Comparacao-PDF.pdf",
    originalPdf: "PDF original",
    modifiedPdf: "PDF modificado",
    extractingText: "Extraindo texto...",
    remove: "Remover",
    uploadOriginalPdf: "Enviar PDF original",
    uploadModifiedPdf: "Enviar PDF modificado",
    dragAndDrop: "Arraste e solte ou clique para procurar",
    generating: "Gerando...",
    report: "Relatório",
    newCompare: "Nova comparação",
    pageOf: "Página {current} de {total}",
    removedWords: "Palavras removidas",
    addedWords: "Palavras adicionadas",
    original: "Original",
    modified: "Modificado",
    noTextContent: "Não há conteúdo de texto nesta página.",
    pageSummary: "Resumo por página",
    same: "Igual",
    word: "palavra",
    words: "palavras",
    pageSingular: "página",
    pagePlural: "páginas",
  },
} as const

function formatCopy(template: string, values: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (_, key) => String(values[key] ?? ""))
}

// ──────────────────────────────────────────────
// Types
// ──────────────────────────────────────────────

type TokenHighlight = "none" | "removed" | "added"

interface DiffToken {
  text: string
  highlight: TokenHighlight
}

interface ParagraphDiff {
  leftTokens: DiffToken[]
  rightTokens: DiffToken[]
  changed: boolean
}

interface PageDiffResult {
  paragraphs: ParagraphDiff[]
  addedWords: number
  removedWords: number
}

interface TextItemLike {
  str: string
  width?: number
  height?: number
  hasEOL?: boolean
  transform: number[]
}

// ──────────────────────────────────────────────
// Smart paragraph extraction from PDF text items
// ──────────────────────────────────────────────

function median(values: number[]): number {
  if (values.length === 0) return 0
  const sorted = [...values].sort((a, b) => a - b)
  return sorted[Math.floor(sorted.length / 2)]
}

function extractParagraphs(items: TextItemLike[]): string[] {
  const filtered = items
    .filter((item) => item.str && item.str.trim().length > 0)
    .map((item) => ({
      text: item.str,
      x: item.transform[4],
      y: item.transform[5],
      width: typeof item.width === "number" ? item.width : 0,
      height: typeof item.height === "number" ? item.height : Math.abs(item.transform[0]) || 12,
      hasEOL: Boolean(item.hasEOL),
    }))

  if (filtered.length === 0) return []

  // Fallback: if all items lack valid transform data, just join as one block
  const hasValidPositions = filtered.some((item) => item.x !== 0 || item.y !== 0)
  if (!hasValidPositions) {
    const text = filtered.map((item) => item.text).join(" ").replace(/\s+/g, " ").trim()
    return text ? [text] : []
  }

  // Sort top-to-bottom, left-to-right
  filtered.sort((a, b) => {
    const yDelta = b.y - a.y
    if (Math.abs(yDelta) > 2.5) return yDelta
    return a.x - b.x
  })

  // Group into lines by y-position
  const lines: Array<{ y: number; text: string }> = []
  let currentLine: typeof filtered = []

  const pushLine = () => {
    if (currentLine.length === 0) return
    currentLine.sort((a, b) => a.x - b.x)
    const chunks: string[] = []
    let prevRight = 0

    currentLine.forEach((item, idx) => {
      const gap = item.x - prevRight
      if (idx > 0 && gap > Math.max(1, item.height * 0.35)) {
        chunks.push(" ")
      }
      chunks.push(item.text)
      prevRight = item.x + item.width
    })

    lines.push({
      y: currentLine[0].y,
      text: chunks.join("").replace(/\s+/g, " ").trim(),
    })
    currentLine = []
  }

  filtered.forEach((item) => {
    const currentY = currentLine[0]?.y
    if (typeof currentY === "number" && Math.abs(currentY - item.y) > 2.5) {
      pushLine()
    }
    currentLine.push(item)
  })
  pushLine()

  // Detect paragraph breaks by line gap
  const lineGaps: number[] = []
  for (let i = 1; i < lines.length; i++) {
    lineGaps.push(Math.abs(lines[i - 1].y - lines[i].y))
  }

  const normalGap = median(lineGaps) || 14
  const paragraphs: string[] = []
  let buffer: string[] = []

  lines.forEach((line, idx) => {
    if (line.text.length === 0) return

    const prevLine = lines[idx - 1]
    const gap = prevLine ? Math.abs(prevLine.y - line.y) : normalGap
    const isNewParagraph = buffer.length > 0 && gap > normalGap * 1.8

    if (isNewParagraph) {
      paragraphs.push(buffer.join(" ").replace(/\s+/g, " ").trim())
      buffer = []
    }

    buffer.push(line.text)
  })

  if (buffer.length > 0) {
    paragraphs.push(buffer.join(" ").replace(/\s+/g, " ").trim())
  }

  const result = paragraphs.filter((p) => p.length > 0)

  // Fallback: if smart paragraph detection returned nothing but we had text items,
  // join all items as a single text block so the diff still works
  if (result.length === 0 && filtered.length > 0) {
    const fallback = filtered.map((item) => item.text).join(" ").replace(/\s+/g, " ").trim()
    return fallback ? [fallback] : []
  }

  // If we ended up with a single giant paragraph (50+ words), it's likely a table/invoice
  // where gap detection didn't find breaks. Split by label-value patterns.
  if (result.length === 1 && countWords(result[0]) >= 50) {
    // Match all-caps labels (2+ chars) optionally followed by a colon/number,
    // e.g. "INVOICE 8342" or "DUE DATE: 01/21/2026" or "TOTAL $500.00"
    const labelPattern = /(?=\b[A-Z][A-Z /]+(?:[:#]|\b))/g
    const parts = result[0].split(labelPattern).map((s) => s.trim()).filter(Boolean)
    if (parts.length > 1) return parts
  }

  return result
}

// ──────────────────────────────────────────────
// Diff logic using the `diff` library
// ──────────────────────────────────────────────

function countWords(text: string): number {
  return text.trim() ? text.trim().split(/\s+/).length : 0
}

/** Diff two paragraph strings word-by-word using the diff library */
function diffParagraph(leftText: string, rightText: string): ParagraphDiff {
  const parts = Diff.diffWords(leftText, rightText)
  const leftTokens: DiffToken[] = []
  const rightTokens: DiffToken[] = []
  let hasChange = false

  for (const part of parts) {
    if (part.added) {
      hasChange = true
      rightTokens.push({ text: part.value, highlight: "added" })
    } else if (part.removed) {
      hasChange = true
      leftTokens.push({ text: part.value, highlight: "removed" })
    } else {
      leftTokens.push({ text: part.value, highlight: "none" })
      rightTokens.push({ text: part.value, highlight: "none" })
    }
  }

  return { leftTokens, rightTokens, changed: hasChange }
}

/** Align paragraphs from both pages using Dice similarity scoring */
function paragraphSimilarity(a: string, b: string): number {
  const wordsA = new Set(a.toLowerCase().match(/[\p{L}\p{N}]+/gu) ?? [])
  const wordsB = new Set(b.toLowerCase().match(/[\p{L}\p{N}]+/gu) ?? [])
  if (wordsA.size === 0 && wordsB.size === 0) return a.trim() === b.trim() ? 1 : 0
  let overlap = 0
  for (const w of wordsA) if (wordsB.has(w)) overlap++
  return (2 * overlap) / (wordsA.size + wordsB.size)
}

function alignParagraphs(leftParas: string[], rightParas: string[]): Array<{ left: string | null; right: string | null }> {
  const m = leftParas.length
  const n = rightParas.length
  const GAP = -0.35

  const scores = Array.from({ length: m + 1 }, () => Array(n + 1).fill(0))
  const trace = Array.from({ length: m + 1 }, () => Array<"match" | "left" | "right" | null>(n + 1).fill(null))

  for (let i = 1; i <= m; i++) { scores[i][0] = i * GAP; trace[i][0] = "left" }
  for (let j = 1; j <= n; j++) { scores[0][j] = j * GAP; trace[0][j] = "right" }

  for (let i = 1; i <= m; i++) {
    for (let j = 1; j <= n; j++) {
      const sim = paragraphSimilarity(leftParas[i - 1], rightParas[j - 1])
      const matchScore = scores[i - 1][j - 1] + sim
      const skipLeft = scores[i - 1][j] + GAP
      const skipRight = scores[i][j - 1] + GAP

      if (matchScore >= skipLeft && matchScore >= skipRight) {
        scores[i][j] = matchScore; trace[i][j] = "match"
      } else if (skipLeft >= skipRight) {
        scores[i][j] = skipLeft; trace[i][j] = "left"
      } else {
        scores[i][j] = skipRight; trace[i][j] = "right"
      }
    }
  }

  const rows: Array<{ left: string | null; right: string | null }> = []
  let i = m, j = n

  while (i > 0 || j > 0) {
    const action = trace[i][j]
    if (action === "match" && i > 0 && j > 0) {
      rows.push({ left: leftParas[i - 1], right: rightParas[j - 1] }); i--; j--
    } else if (action === "left" && i > 0) {
      rows.push({ left: leftParas[i - 1], right: null }); i--
    } else if (j > 0) {
      rows.push({ left: null, right: rightParas[j - 1] }); j--
    } else {
      break
    }
  }

  return rows.reverse()
}

/** Build full page diff: align paragraphs, then word-diff each pair */
function buildPageDiff(leftParas: string[], rightParas: string[]): PageDiffResult {
  const aligned = alignParagraphs(leftParas, rightParas)
  const paragraphs: ParagraphDiff[] = []
  let addedWords = 0
  let removedWords = 0

  for (const pair of aligned) {
    const leftText = pair.left ?? ""
    const rightText = pair.right ?? ""
    const diff = diffParagraph(leftText, rightText)
    paragraphs.push(diff)

    // Count changed words
    for (const t of diff.leftTokens) if (t.highlight === "removed") removedWords += countWords(t.text)
    for (const t of diff.rightTokens) if (t.highlight === "added") addedWords += countWords(t.text)
  }

  return { paragraphs, addedWords, removedWords }
}

// ──────────────────────────────────────────────
// Render helpers
// ──────────────────────────────────────────────

function renderTokens(tokens: DiffToken[], emptyLabel: string) {
  if (tokens.length === 0) {
    return <span className="italic text-slate-400">{emptyLabel}</span>
  }

  return tokens.map((token, index) => {
    if (token.highlight === "none") {
      return <span key={index}>{token.text}</span>
    }

    return (
      <span
        key={index}
        className={cn(
          "rounded-sm px-[1px]",
          token.highlight === "removed" && "bg-red-200 text-red-900",
          token.highlight === "added" && "bg-green-200 text-green-900"
        )}
      >
        {token.text}
      </span>
    )
  })
}

// ──────────────────────────────────────────────
// Component
// ──────────────────────────────────────────────

export function PdfCompareInterface({ locale = "en" }: { locale?: ToolLocale }) {
  const router = useRouter()
  const copy = PDF_COMPARE_COPY[locale]

  const [userPlan, setUserPlan] = useState("loading")
  const [fileA, setFileA] = useState<File | null>(null)
  const [fileB, setFileB] = useState<File | null>(null)
  const [isDragOverA, setIsDragOverA] = useState(false)
  const [isDragOverB, setIsDragOverB] = useState(false)
  const [paraPagesA, setParaPagesA] = useState<string[][]>([])
  const [paraPagesB, setParaPagesB] = useState<string[][]>([])
  const [currentPage, setCurrentPage] = useState(0)
  const [isLoadingA, setIsLoadingA] = useState(false)
  const [isLoadingB, setIsLoadingB] = useState(false)
  const [errorMessage, setErrorMessage] = useState("")

  const totalPagesA = paraPagesA.length
  const totalPagesB = paraPagesB.length
  const maxPages = Math.max(totalPagesA, totalPagesB)
  const hasBothFiles = totalPagesA > 0 && totalPagesB > 0
  const isBusinessUser = userPlan === "business" || userPlan === "enterprise"

  useEffect(() => {
    fetch("/api/user-plan")
      .then((response) => response.json())
      .then((data) => setUserPlan(data.plan || "free"))
      .catch(() => setUserPlan("free"))
  }, [])

  const extractPages = useCallback(async (pdfFile: File): Promise<string[][]> => {
    const pdfjsLib = await import("pdfjs-dist")
    pdfjsLib.GlobalWorkerOptions.workerSrc = "/pdf.worker.min.mjs"

    const pdf = await pdfjsLib.getDocument({ data: await pdfFile.arrayBuffer() }).promise
    const pages: string[][] = []

    for (let p = 1; p <= pdf.numPages; p++) {
      const page = await pdf.getPage(p)
      const content = await page.getTextContent()
      pages.push(extractParagraphs(content.items as TextItemLike[]))
    }

    return pages
  }, [])

  const handlePdfLoad = useCallback(
    async (file: File, side: "left" | "right") => {
      if (file.type !== "application/pdf" && !file.name.toLowerCase().endsWith(".pdf")) {
        setErrorMessage(copy.invalidPdf)
        return
      }
      if (file.size === 0) {
        setErrorMessage("This file is empty. Please upload a PDF with content.")
        return
      }

      const setLoading = side === "left" ? setIsLoadingA : setIsLoadingB
      setLoading(true)
      setErrorMessage("")

      try {
        const pages = await extractPages(file)

        if (pages.length === 0) {
          setErrorMessage(side === "left" ? copy.originalPdfEmpty : copy.modifiedPdfEmpty)
          return
        }

        if (side === "left") {
          setFileA(file)
          setParaPagesA(pages)
        } else {
          setFileB(file)
          setParaPagesB(pages)
        }

        setCurrentPage(0)
      } catch (err: unknown) {
        // Surface specific pdfjs errors so the user knows what's wrong.
        const errName = (err as { name?: string })?.name || ""
        const errMsg = err instanceof Error ? err.message : String(err)
        let friendly: string
        if (errName === "PasswordException" || /password/i.test(errMsg)) {
          friendly = "This PDF is password-protected. Remove the password and try again."
        } else if (errName === "InvalidPDFException" || /invalid\s*pdf/i.test(errMsg)) {
          friendly = "This file is not a valid PDF. Please upload a real PDF."
        } else {
          friendly = side === "left" ? copy.originalPdfReadFailed : copy.modifiedPdfReadFailed
        }
        setErrorMessage(friendly)
      } finally {
        setLoading(false)
      }
    },
    [copy.invalidPdf, copy.modifiedPdfEmpty, copy.modifiedPdfReadFailed, copy.originalPdfEmpty, copy.originalPdfReadFailed, extractPages]
  )

  const pageResults = useMemo(
    () => {
      if (!hasBothFiles) return []
      return Array.from({ length: maxPages }, (_, index) =>
        buildPageDiff(paraPagesA[index] ?? [], paraPagesB[index] ?? [])
      )
    },
    [hasBothFiles, maxPages, paraPagesA, paraPagesB]
  )

  const resetInterface = useCallback(() => {
    setFileA(null)
    setFileB(null)
    setParaPagesA([])
    setParaPagesB([])
    setCurrentPage(0)
    setIsLoadingA(false)
    setIsLoadingB(false)
    setIsGeneratingReport(false)
    setErrorMessage("")
  }, [])

  const [isGeneratingReport, setIsGeneratingReport] = useState(false)

  const downloadDiffReport = useCallback(async () => {
    setIsGeneratingReport(true)
    try {
      const totalAdded = pageResults.reduce((sum, page) => sum + page.addedWords, 0)
      const totalRemoved = pageResults.reduce((sum, page) => sum + page.removedWords, 0)
      const totalChanges = totalAdded + totalRemoved
      const overallLabel =
        totalChanges === 0 ? copy.identical :
        totalChanges <= 40 ? copy.minorChanges :
        totalChanges <= 150 ? copy.moderateChanges : copy.majorChanges

      const pdfDoc = await PDFDocument.create()
      const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica)
      const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
      const courier = await pdfDoc.embedFont(StandardFonts.Courier)

      const W = 612 // Letter width in points
      const H = 792 // Letter height
      const MARGIN = 50
      const CONTENT_W = W - MARGIN * 2

      const BRAND_COLOR = rgb(0.31, 0.31, 0.82)  // indigo
      const RED = rgb(0.8, 0.15, 0.15)
      const GREEN = rgb(0.1, 0.55, 0.1)
      const DARK = rgb(0.15, 0.15, 0.2)
      const GRAY = rgb(0.4, 0.4, 0.45)
      const LIGHT_GRAY = rgb(0.92, 0.92, 0.94)
      const WHITE = rgb(1, 1, 1)

      // ── Helper: sanitize text to WinAnsi-safe characters ──
      // pdf-lib standard fonts only support WinAnsi encoding.
      // Replace unsupported characters so drawText never crashes.
      function safe(text: string): string {
        return text
          .replace(/[\u2014\u2013]/g, "-")     // em/en dash -> hyphen
          .replace(/[\u2018\u2019]/g, "'")     // smart single quotes
          .replace(/[\u201C\u201D]/g, '"')     // smart double quotes
          .replace(/\u2026/g, "...")            // ellipsis
          .replace(/\u2022/g, "-")             // bullet
          .replace(/[^\x00-\xFF]/g, "?")       // anything outside Latin-1 -> ?
      }

      // ── Helper: wrap text into lines that fit a given width ──
      function wrapText(text: string, font: typeof helvetica, fontSize: number, maxWidth: number): string[] {
        const words = safe(text).split(/\s+/)
        const lines: string[] = []
        let currentLine = ""

        for (const word of words) {
          const testLine = currentLine ? `${currentLine} ${word}` : word
          const testWidth = font.widthOfTextAtSize(testLine, fontSize)
          if (testWidth > maxWidth && currentLine) {
            lines.push(currentLine)
            currentLine = word
          } else {
            currentLine = testLine
          }
        }
        if (currentLine) lines.push(currentLine)
        return lines.length > 0 ? lines : [""]
      }

      // ── Helper: draw a rectangle with optional border ──
      function drawBox(page: ReturnType<typeof pdfDoc.addPage>, x: number, y: number, w: number, h: number, color: ReturnType<typeof rgb>, borderColor?: ReturnType<typeof rgb>) {
        page.drawRectangle({ x, y, width: w, height: h, color })
        if (borderColor) {
          page.drawRectangle({ x, y, width: w, height: h, borderColor, borderWidth: 0.5 })
        }
      }

      // ── Helper: add footer to a page ──
      function addFooter(page: ReturnType<typeof pdfDoc.addPage>, pageNum: number, totalPages: number) {
        const footerY = 30
        page.drawLine({ start: { x: MARGIN, y: footerY + 12 }, end: { x: W - MARGIN, y: footerY + 12 }, thickness: 0.5, color: LIGHT_GRAY })
        page.drawText("pdf.it.com/pdf-compare", { x: MARGIN, y: footerY, size: 7, font: helvetica, color: GRAY })
        const pageLabel = formatCopy(copy.pageOf, { current: pageNum, total: totalPages })
        const pageLabelWidth = helvetica.widthOfTextAtSize(pageLabel, 7)
        page.drawText(pageLabel, { x: W - MARGIN - pageLabelWidth, y: footerY, size: 7, font: helvetica, color: GRAY })
      }

      // ── Helper: draw the table header row ──
      function drawTableHeader(page: ReturnType<typeof pdfDoc.addPage>, atY: number) {
        drawBox(page, MARGIN, atY - 18, CONTENT_W, 18, BRAND_COLOR)
        page.drawText(copy.reportPage, { x: MARGIN + 10, y: atY - 13, size: 8, font: helveticaBold, color: WHITE })
        page.drawText(copy.reportStatus, { x: MARGIN + 80, y: atY - 13, size: 8, font: helveticaBold, color: WHITE })
        page.drawText(copy.reportAdded, { x: MARGIN + 260, y: atY - 13, size: 8, font: helveticaBold, color: WHITE })
        page.drawText(copy.reportRemoved, { x: MARGIN + 340, y: atY - 13, size: 8, font: helveticaBold, color: WHITE })
        page.drawText(copy.reportTotal, { x: MARGIN + 430, y: atY - 13, size: 8, font: helveticaBold, color: WHITE })
      }

      // ════════════════════════════════════════════════
      // PAGE 1: Cover / Summary
      // ════════════════════════════════════════════════
      let currentCoverPage = pdfDoc.addPage([W, H])

      // Header bar
      drawBox(currentCoverPage, 0, H - 80, W, 80, BRAND_COLOR)
      currentCoverPage.drawText(copy.reportTitle, { x: MARGIN, y: H - 52, size: 20, font: helveticaBold, color: WHITE })
      currentCoverPage.drawText(copy.reportGeneratedBy, { x: MARGIN, y: H - 68, size: 9, font: helvetica, color: rgb(0.8, 0.8, 1) })

      let y = H - 120

      // Date
      const localeTag = locale === "es" ? "es-ES" : locale === "br" ? "pt-BR" : "en-US"
      const dateStr = new Date().toLocaleDateString(localeTag, { year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" })
      currentCoverPage.drawText(dateStr, { x: MARGIN, y, size: 9, font: helvetica, color: GRAY })
      y -= 30

      // Document info box
      const nameA = safe(fileA?.name || "-")
      const nameB = safe(fileB?.name || "-")
      drawBox(currentCoverPage, MARGIN, y - 70, CONTENT_W, 70, rgb(0.97, 0.97, 0.99), LIGHT_GRAY)
      currentCoverPage.drawText(locale === "es" ? "DOCUMENTOS COMPARADOS" : locale === "br" ? "DOCUMENTOS COMPARADOS" : "DOCUMENTS COMPARED", { x: MARGIN + 15, y: y - 18, size: 8, font: helveticaBold, color: BRAND_COLOR })
      currentCoverPage.drawText(`${copy.original}:`, { x: MARGIN + 15, y: y - 35, size: 9, font: helveticaBold, color: DARK })
      currentCoverPage.drawText(`${nameA}  (${totalPagesA} ${totalPagesA === 1 ? copy.pageSingular : copy.pagePlural})`, { x: MARGIN + 75, y: y - 35, size: 9, font: helvetica, color: DARK })
      currentCoverPage.drawText(`${copy.modified}:`, { x: MARGIN + 15, y: y - 52, size: 9, font: helveticaBold, color: DARK })
      currentCoverPage.drawText(`${nameB}  (${totalPagesB} ${totalPagesB === 1 ? copy.pageSingular : copy.pagePlural})`, { x: MARGIN + 75, y: y - 52, size: 9, font: helvetica, color: DARK })
      y -= 100

      // Summary stats
      currentCoverPage.drawText(locale === "es" ? "RESUMEN" : locale === "br" ? "RESUMO" : "SUMMARY", { x: MARGIN, y, size: 11, font: helveticaBold, color: DARK })
      y -= 20

      // Stats boxes (3 columns)
      const boxW = (CONTENT_W - 20) / 3
      const statsData = [
        { label: locale === "es" ? "Evaluación" : locale === "br" ? "Avaliação" : "Assessment", value: overallLabel, color: totalChanges === 0 ? GREEN : totalChanges <= 150 ? rgb(0.75, 0.55, 0) : RED },
        { label: copy.addedWords, value: `+${totalAdded}`, color: GREEN },
        { label: copy.removedWords, value: `-${totalRemoved}`, color: RED },
      ]
      statsData.forEach((stat, i) => {
        const bx = MARGIN + i * (boxW + 10)
        drawBox(currentCoverPage, bx, y - 50, boxW, 50, rgb(0.97, 0.97, 0.99), LIGHT_GRAY)
        currentCoverPage.drawText(stat.label, { x: bx + 10, y: y - 18, size: 7, font: helveticaBold, color: GRAY })
        currentCoverPage.drawText(stat.value, { x: bx + 10, y: y - 38, size: 16, font: helveticaBold, color: stat.color })
      })
      y -= 80

      // Page-by-page overview table
      currentCoverPage.drawText(locale === "es" ? "RESUMEN PAGINA POR PAGINA" : locale === "br" ? "RESUMO PAGINA POR PAGINA" : "PAGE-BY-PAGE OVERVIEW", { x: MARGIN, y, size: 11, font: helveticaBold, color: DARK })
      y -= 20

      // Table header
      drawTableHeader(currentCoverPage, y)
      y -= 18

      pageResults.forEach((page, idx) => {
        const changes = page.addedWords + page.removedWords
        const status =
          changes === 0 ? copy.identical :
          changes <= 20 ? copy.minorChanges :
          changes <= 80 ? copy.moderateChanges : copy.majorChanges
        const statusColor = changes === 0 ? GREEN : changes <= 80 ? rgb(0.75, 0.55, 0) : RED
        const rowBg = idx % 2 === 0 ? rgb(0.98, 0.98, 1) : WHITE

        // Overflow to new page if needed
        if (y < 60) {
          currentCoverPage = pdfDoc.addPage([W, H])
          y = H - 50
          drawTableHeader(currentCoverPage, y)
          y -= 18
        }

        drawBox(currentCoverPage, MARGIN, y - 18, CONTENT_W, 18, rowBg)
        currentCoverPage.drawText(`${copy.reportPage} ${idx + 1}`, { x: MARGIN + 10, y: y - 13, size: 8, font: helvetica, color: DARK })
        currentCoverPage.drawText(status, { x: MARGIN + 80, y: y - 13, size: 8, font: helveticaBold, color: statusColor })
        currentCoverPage.drawText(`+${page.addedWords}`, { x: MARGIN + 260, y: y - 13, size: 8, font: courier, color: GREEN })
        currentCoverPage.drawText(`-${page.removedWords}`, { x: MARGIN + 340, y: y - 13, size: 8, font: courier, color: RED })
        currentCoverPage.drawText(`${changes}`, { x: MARGIN + 430, y: y - 13, size: 8, font: courier, color: DARK })
        y -= 18
      })

      // ════════════════════════════════════════════════
      // DETAIL PAGES: One per compared page with changes
      // ════════════════════════════════════════════════

      pageResults.forEach((page, pageIdx) => {
        const changes = page.addedWords + page.removedWords
        if (changes === 0) return

        let dp = pdfDoc.addPage([W, H])

        // Detail page header helper
        function drawDetailHeader(p: typeof dp, label: string) {
          drawBox(p, 0, H - 50, W, 50, rgb(0.95, 0.95, 0.98))
          p.drawLine({ start: { x: 0, y: H - 50 }, end: { x: W, y: H - 50 }, thickness: 2, color: BRAND_COLOR })
          p.drawText(safe(label), { x: MARGIN, y: H - 35, size: 13, font: helveticaBold, color: DARK })

          const sLabel =
            changes <= 20 ? copy.minorChanges :
            changes <= 80 ? copy.moderateChanges : copy.majorChanges
          const sColor = changes <= 80 ? rgb(0.75, 0.55, 0) : RED
          const sW = helveticaBold.widthOfTextAtSize(sLabel, 9)
          p.drawText(sLabel, { x: W - MARGIN - sW, y: H - 35, size: 9, font: helveticaBold, color: sColor })
        }

        drawDetailHeader(dp, `${copy.reportPage} ${pageIdx + 1} - ${copy.reportDetailedChanges}`)

        let dy = H - 75

        // Stats line
        dp.drawText(`+${page.addedWords} ${copy.reportAdded.toLowerCase()}`, { x: MARGIN, y: dy, size: 8, font: helveticaBold, color: GREEN })
        dp.drawText(`-${page.removedWords} ${copy.reportRemoved.toLowerCase()}`, { x: MARGIN + 90, y: dy, size: 8, font: helveticaBold, color: RED })
        dy -= 20

        page.paragraphs.forEach((para, pIdx) => {
          if (!para.changed) return

          const removedTokens = para.leftTokens.filter((t) => t.highlight === "removed")
          const addedTokens = para.rightTokens.filter((t) => t.highlight === "added")
          if (removedTokens.length === 0 && addedTokens.length === 0) return

          // Check if we need a new page
          if (dy < 100) {
            dp = pdfDoc.addPage([W, H])
            drawDetailHeader(dp, `${copy.reportPage} ${pageIdx + 1} - ${copy.reportDetailedChanges} (${copy.reportContinued})`)
            dy = H - 75
          }

          // Section label
          dp.drawText(`${copy.reportChange} ${pIdx + 1}`, { x: MARGIN, y: dy, size: 9, font: helveticaBold, color: DARK })
          dy -= 5

          // Removed text block
          if (removedTokens.length > 0) {
            const removedText = removedTokens.map((t) => t.text.trim()).join("  ")
            const removedLines = wrapText(removedText, helvetica, 8, CONTENT_W - 30)

            const blockH = Math.max(22, removedLines.length * 12 + 10)
            if (dy - blockH < 60) {
              dp = pdfDoc.addPage([W, H])
              drawDetailHeader(dp, `${copy.reportPage} ${pageIdx + 1} - ${copy.reportDetailedChanges} (${copy.reportContinued})`)
              dy = H - 75
            }

            drawBox(dp, MARGIN, dy - blockH, CONTENT_W, blockH, rgb(1, 0.95, 0.95), rgb(0.9, 0.8, 0.8))
            dp.drawText(copy.reportRemovedLabel, { x: MARGIN + 8, y: dy - 12, size: 6, font: helveticaBold, color: RED })
            removedLines.forEach((line, li) => {
              dp.drawText(line, { x: MARGIN + 8, y: dy - 22 - li * 12, size: 8, font: helvetica, color: rgb(0.5, 0.1, 0.1) })
            })
            dy -= blockH + 5
          }

          // Added text block
          if (addedTokens.length > 0) {
            const addedText = addedTokens.map((t) => t.text.trim()).join("  ")
            const addedLines = wrapText(addedText, helvetica, 8, CONTENT_W - 30)

            const blockH = Math.max(22, addedLines.length * 12 + 10)
            if (dy - blockH < 60) {
              dp = pdfDoc.addPage([W, H])
              drawDetailHeader(dp, `${copy.reportPage} ${pageIdx + 1} - ${copy.reportDetailedChanges} (${copy.reportContinued})`)
              dy = H - 75
            }

            drawBox(dp, MARGIN, dy - blockH, CONTENT_W, blockH, rgb(0.95, 1, 0.95), rgb(0.8, 0.9, 0.8))
            dp.drawText(copy.reportAddedLabel, { x: MARGIN + 8, y: dy - 12, size: 6, font: helveticaBold, color: GREEN })
            addedLines.forEach((line, li) => {
              dp.drawText(line, { x: MARGIN + 8, y: dy - 22 - li * 12, size: 8, font: helvetica, color: rgb(0.1, 0.35, 0.1) })
            })
            dy -= blockH + 5
          }

          dy -= 10
        })
      })

      // Add footers to all pages
      const allPages = pdfDoc.getPages()
      const totalDocPages = allPages.length
      allPages.forEach((p, i) => addFooter(p, i + 1, totalDocPages))

      // Download
      const pdfBytes = await pdfDoc.save()
      const blob = new Blob([pdfBytes], { type: "application/pdf" })
      const url = URL.createObjectURL(blob)
      const link = document.createElement("a")
      link.href = url
      link.download = copy.reportFileName
      link.click()
      URL.revokeObjectURL(url)
    } catch (err) {
      console.error("Report generation failed:", err)
      setErrorMessage(copy.reportGenerationFailed)
    } finally {
      setIsGeneratingReport(false)
    }
  }, [copy, fileA, fileB, locale, pageResults, totalPagesA, totalPagesB])

  // ──── Render states ────

  // Check for upgrade/limit errors before other states
  const isUpgradeError = (errorMessage || "").includes("upgrade_required")
  const isLimitError = (errorMessage || "").toLowerCase().includes("daily limit reached") || (errorMessage || "").includes("daily_limit_reached")
  const isSignupError = (errorMessage || "").includes("signup_required")

  if (isSignupError) {
    router.push(copy.signupPath)
    return null
  }

  if (isUpgradeError || isLimitError) {
    return (
      <section className="py-16" style={{ background: "radial-gradient(ellipse 60% 40% at 50% 0%, rgba(107,124,255,0.06) 0%, transparent 50%), radial-gradient(ellipse 50% 50% at 100% 80%, rgba(232,129,58,0.03) 0%, transparent 50%), #0E0F1E" }}>
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-lg mx-auto relative">
            <div className="rounded-2xl p-[1px]" style={{ background: "linear-gradient(135deg, rgba(107,124,255,0.5), rgba(20,216,196,0.25), rgba(107,124,255,0.35), rgba(232,129,58,0.2), rgba(107,124,255,0.4))" }}>
              <div className="rounded-[15px] p-8 pt-10 text-center relative overflow-hidden" style={{ background: "radial-gradient(ellipse 40% 30% at 50% 0%, rgba(107,124,255,0.06) 0%, transparent 50%), radial-gradient(ellipse 70% 60% at 95% 90%, rgba(232,129,58,0.04) 0%, transparent 70%), radial-gradient(ellipse 50% 50% at 5% 10%, rgba(20,216,196,0.03) 0%, transparent 60%), rgba(255, 255, 255, 0.07)", backdropFilter: "blur(12px)", WebkitBackdropFilter: "blur(12px)", boxShadow: "inset 0 -1px 1px rgba(107,124,255,0.08), 0 4px 24px rgba(0,0,0,0.3)" }}>
                <div className="absolute top-0 left-1/2 -translate-x-1/2 px-4 py-1 rounded-b-lg text-[10px] font-bold uppercase tracking-widest" style={{ background: "linear-gradient(135deg, #6B7CFF, #8B9AFF)", color: "#0E0F1E" }}>Business Feature</div>
                <div className="w-14 h-14 rounded-xl flex items-center justify-center mx-auto mb-4" style={{ background: "linear-gradient(135deg, #1a1f5e, #252A6A)", boxShadow: "0 0 20px rgba(107,124,255,0.3), 0 4px 8px rgba(0,0,0,0.2)" }}>
                  <Crown className="h-7 w-7 text-[#6B7CFF]" />
                </div>
                <h2 className="text-xl font-bold text-white mb-2">
                  {isUpgradeError ? copy.upgradeTitle : copy.limitTitle}
                </h2>
                <p className="text-sm text-slate-400 mb-6">
                  {isUpgradeError ? copy.upgradeDescription : copy.limitDescription}
                </p>
                <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
                  <Button onClick={() => router.push(copy.pricingPath)} className="bg-[#14D8C4] hover:bg-[#2EE6D6] text-[#0E0F1E] font-bold px-8 py-3 rounded-xl">
                    {copy.upgradeLabel}
                  </Button>
                  <Button onClick={resetInterface} variant="outline" className="border border-slate-600 text-slate-300 hover:text-white rounded-xl px-6 py-3">
                    {copy.goBack}
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    )
  }

  if (userPlan === "loading") {
    return (
      <section className="py-16">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-2xl mx-auto text-center">
            <Loader2 className="h-10 w-10 text-indigo-600 animate-spin mx-auto mb-4" />
            <p className="text-slate-600 font-medium">{copy.loading}</p>
          </div>
        </div>
      </section>
    )
  }

  if (!isBusinessUser) {
    return (
      <section className="py-16" style={{ background: "radial-gradient(ellipse 60% 40% at 50% 0%, rgba(107,124,255,0.06) 0%, transparent 50%), radial-gradient(ellipse 50% 50% at 100% 80%, rgba(232,129,58,0.03) 0%, transparent 50%), #0E0F1E" }}>
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-lg mx-auto relative">
            <div className="rounded-2xl p-[1px]" style={{ background: "linear-gradient(135deg, rgba(107,124,255,0.5), rgba(20,216,196,0.25), rgba(107,124,255,0.35), rgba(232,129,58,0.2), rgba(107,124,255,0.4))" }}>
              <div className="rounded-[15px] p-8 pt-10 text-center relative overflow-hidden" style={{ background: "radial-gradient(ellipse 40% 30% at 50% 0%, rgba(107,124,255,0.06) 0%, transparent 50%), radial-gradient(ellipse 70% 60% at 95% 90%, rgba(232,129,58,0.04) 0%, transparent 70%), radial-gradient(ellipse 50% 50% at 5% 10%, rgba(20,216,196,0.03) 0%, transparent 60%), rgba(255, 255, 255, 0.07)", backdropFilter: "blur(12px)", WebkitBackdropFilter: "blur(12px)", boxShadow: "inset 0 -1px 1px rgba(107,124,255,0.08), 0 4px 24px rgba(0,0,0,0.3)" }}>
                <div className="absolute top-0 left-1/2 -translate-x-1/2 px-4 py-1 rounded-b-lg text-[10px] font-bold uppercase tracking-widest" style={{ background: "linear-gradient(135deg, #6B7CFF, #8B9AFF)", color: "#0E0F1E" }}>Business Feature</div>
                <div className="w-14 h-14 rounded-xl flex items-center justify-center mx-auto mb-4" style={{ background: "linear-gradient(135deg, #1a1f5e, #252A6A)", boxShadow: "0 0 20px rgba(107,124,255,0.3), 0 4px 8px rgba(0,0,0,0.2)" }}>
                  <Crown className="h-7 w-7 text-[#6B7CFF]" />
                </div>
                <h2 className="text-xl font-bold text-white mb-2">{copy.businessFeature}</h2>
                <p className="text-sm text-slate-400 mb-6">{copy.businessDescription}</p>
                <Button onClick={() => router.push(copy.pricingSourcePath)} className="bg-[#14D8C4] hover:bg-[#2EE6D6] text-[#0E0F1E] font-bold px-8 py-3 rounded-xl">{copy.upgradeButton}</Button>
              </div>
            </div>
          </div>
        </div>
      </section>
    )
  }

  if (!hasBothFiles) {
    return (
      <section className="py-16">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-4xl mx-auto">
            {errorMessage && (
              <div className="mb-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
                {errorMessage}
              </div>
            )}

            <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
              <div>
                <h3 className="font-bold text-slate-900 mb-3 text-center">{copy.originalPdf}</h3>
                {isLoadingA ? (
                  <div className="border-2 border-indigo-300 bg-indigo-50 rounded-xl p-8 text-center">
                    <Loader2 className="h-10 w-10 text-indigo-600 animate-spin mx-auto mb-3" />
                    <p className="font-medium text-slate-700">{copy.extractingText}</p>
                  </div>
                ) : fileA && totalPagesA > 0 ? (
                  <div className="border-2 border-green-400 bg-green-50 rounded-xl p-6 text-center">
                    <CheckCircle className="h-10 w-10 text-green-600 mx-auto mb-3" />
                    <p className="font-bold text-slate-900 truncate">{fileA.name}</p>
                    <p className="text-sm text-slate-500">{totalPagesA} {totalPagesA === 1 ? copy.pageSingular : copy.pagePlural}</p>
                    <Button
                      size="sm"
                      variant="outline"
                      className="mt-3 text-xs"
                      onClick={() => { setFileA(null); setParaPagesA([]); setErrorMessage("") }}
                    >
                      <X className="h-3 w-3 mr-1" /> {copy.remove}
                    </Button>
                  </div>
                ) : (
                  <div
                    className={cn(
                      "border-2 border-dashed rounded-xl p-8 transition-all duration-200 cursor-pointer text-center",
                      isDragOverA ? "border-indigo-500 bg-indigo-50" : "border-gray-300 hover:border-indigo-400 hover:bg-gray-50"
                    )}
                    onDragOver={(e) => { e.preventDefault(); setIsDragOverA(true) }}
                    onDragLeave={(e) => { e.preventDefault(); setIsDragOverA(false) }}
                    onDrop={(e) => { e.preventDefault(); setIsDragOverA(false); const f = e.dataTransfer.files[0]; if (f) void handlePdfLoad(f, "left") }}
                    onClick={() => document.getElementById("compare-file-a")?.click()}
                  >
                    <Upload className="h-10 w-10 text-indigo-500 mx-auto mb-3" />
                    <p className="font-bold text-slate-900 mb-1">{copy.uploadOriginalPdf}</p>
                    <p className="text-sm text-slate-500">{copy.dragAndDrop}</p>
                  </div>
                )}
                <input id="compare-file-a" type="file" accept=".pdf,application/pdf" className="hidden" onChange={(e) => { const f = e.target.files?.[0]; if (f) void handlePdfLoad(f, "left") }} />
              </div>

              <div>
                <h3 className="font-bold text-slate-900 mb-3 text-center">{copy.modifiedPdf}</h3>
                {isLoadingB ? (
                  <div className="border-2 border-indigo-300 bg-indigo-50 rounded-xl p-8 text-center">
                    <Loader2 className="h-10 w-10 text-indigo-600 animate-spin mx-auto mb-3" />
                    <p className="font-medium text-slate-700">{copy.extractingText}</p>
                  </div>
                ) : fileB && totalPagesB > 0 ? (
                  <div className="border-2 border-green-400 bg-green-50 rounded-xl p-6 text-center">
                    <CheckCircle className="h-10 w-10 text-green-600 mx-auto mb-3" />
                    <p className="font-bold text-slate-900 truncate">{fileB.name}</p>
                    <p className="text-sm text-slate-500">{totalPagesB} {totalPagesB === 1 ? copy.pageSingular : copy.pagePlural}</p>
                    <Button
                      size="sm"
                      variant="outline"
                      className="mt-3 text-xs"
                      onClick={() => { setFileB(null); setParaPagesB([]); setErrorMessage("") }}
                    >
                      <X className="h-3 w-3 mr-1" /> {copy.remove}
                    </Button>
                  </div>
                ) : (
                  <div
                    className={cn(
                      "border-2 border-dashed rounded-xl p-8 transition-all duration-200 cursor-pointer text-center",
                      isDragOverB ? "border-indigo-500 bg-indigo-50" : "border-gray-300 hover:border-indigo-400 hover:bg-gray-50"
                    )}
                    onDragOver={(e) => { e.preventDefault(); setIsDragOverB(true) }}
                    onDragLeave={(e) => { e.preventDefault(); setIsDragOverB(false) }}
                    onDrop={(e) => { e.preventDefault(); setIsDragOverB(false); const f = e.dataTransfer.files[0]; if (f) void handlePdfLoad(f, "right") }}
                    onClick={() => document.getElementById("compare-file-b")?.click()}
                  >
                    <Upload className="h-10 w-10 text-indigo-500 mx-auto mb-3" />
                    <p className="font-bold text-slate-900 mb-1">{copy.uploadModifiedPdf}</p>
                    <p className="text-sm text-slate-500">{copy.dragAndDrop}</p>
                  </div>
                )}
                <input id="compare-file-b" type="file" accept=".pdf,application/pdf" className="hidden" onChange={(e) => { const f = e.target.files?.[0]; if (f) void handlePdfLoad(f, "right") }} />
              </div>
            </div>

            <TrustBadges />
          </div>
        </div>
      </section>
    )
  }

  // ──── Comparison view ────

  const current = pageResults[currentPage]
  const totalChanges = (current?.addedWords ?? 0) + (current?.removedWords ?? 0)
  const diffLabel =
    totalChanges === 0 ? copy.identical :
    totalChanges <= 20 ? copy.minorChanges :
    totalChanges <= 80 ? copy.moderateChanges :
    copy.majorChanges
  const diffColor =
    totalChanges === 0 ? "text-green-600" :
    totalChanges <= 20 ? "text-yellow-600" :
    totalChanges <= 80 ? "text-[#14D8C4]" :
    "text-red-600"

  return (
    <section className="py-8">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          {/* Toolbar */}
          <div className="bg-white border border-gray-200 rounded-xl p-4 mb-4 flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-4 min-w-0">
              <div className="flex items-center gap-2 text-sm min-w-0">
                <FileText className="h-4 w-4 text-red-500 shrink-0" />
                <span className="font-medium text-slate-700 truncate">{fileA?.name}</span>
              </div>
              <ArrowLeftRight className="h-4 w-4 text-slate-400 shrink-0" />
              <div className="flex items-center gap-2 text-sm min-w-0">
                <FileText className="h-4 w-4 text-green-500 shrink-0" />
                <span className="font-medium text-slate-700 truncate">{fileB?.name}</span>
              </div>
            </div>

            <div className="flex items-center gap-3">
              <Button variant="outline" size="sm" onClick={downloadDiffReport} disabled={isGeneratingReport} className="text-xs">
                {isGeneratingReport ? (
                  <><Loader2 className="h-3 w-3 mr-1 animate-spin" /> {copy.generating}</>
                ) : (
                  <><Download className="h-3 w-3 mr-1" /> {copy.report}</>
                )}
              </Button>
              <Button variant="outline" size="sm" onClick={resetInterface} className="text-xs">
                <X className="h-3 w-3 mr-1" /> {copy.newCompare}
              </Button>
            </div>
          </div>

          {errorMessage && (
            <div className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
              {errorMessage}
            </div>
          )}

          {/* Page navigation */}
          <div className="bg-white border border-gray-200 rounded-xl p-3 mb-4 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" disabled={currentPage === 0} onClick={() => setCurrentPage((p) => p - 1)}>
                <ChevronLeft className="h-4 w-4" />
              </Button>
              <span className="text-sm font-medium text-slate-700 min-w-[90px] text-center">
                {formatCopy(copy.pageOf, { current: currentPage + 1, total: maxPages })}
              </span>
              <Button variant="outline" size="sm" disabled={currentPage >= maxPages - 1} onClick={() => setCurrentPage((p) => p + 1)}>
                <ChevronRight className="h-4 w-4" />
              </Button>
            </div>

            <div className="flex items-center gap-3">
              <span className={cn("text-sm font-bold", diffColor)}>{diffLabel}</span>
              <span className="text-xs text-slate-500">
                +{current?.addedWords ?? 0} / -{current?.removedWords ?? 0}
              </span>
            </div>
          </div>

          {/* Legend */}
          <div className="flex flex-wrap gap-4 mb-4 text-xs font-medium">
            <span className="flex items-center gap-1.5">
              <span className="w-3 h-3 rounded bg-red-200 border border-red-300"></span>
              {copy.removedWords}
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-3 h-3 rounded bg-green-200 border border-green-300"></span>
              {copy.addedWords}
            </span>
          </div>

          {/* Side-by-side paragraph diff */}
          {current && (
            <div className="border border-gray-200 rounded-xl overflow-hidden bg-white">
              <div className="grid grid-cols-2 divide-x divide-gray-200 bg-gray-50 border-b border-gray-200">
                <div className="px-4 py-2 text-xs font-bold text-red-600 uppercase tracking-wide">{copy.original}</div>
                <div className="px-4 py-2 text-xs font-bold text-green-600 uppercase tracking-wide">{copy.modified}</div>
              </div>

              <div className="max-h-[650px] overflow-y-auto divide-y divide-gray-100">
                {current.paragraphs.map((para, idx) => (
                  <div key={idx} className="grid grid-cols-2 divide-x divide-gray-200">
                    <div className={cn("px-4 py-3 text-sm leading-7 break-words", para.changed ? "bg-red-50/40" : "bg-white")}>
                      <p className="whitespace-pre-wrap text-slate-800">
                        {renderTokens(para.leftTokens, "")}
                      </p>
                    </div>
                    <div className={cn("px-4 py-3 text-sm leading-7 break-words", para.changed ? "bg-green-50/40" : "bg-white")}>
                      <p className="whitespace-pre-wrap text-slate-800">
                        {renderTokens(para.rightTokens, "")}
                      </p>
                    </div>
                  </div>
                ))}

                {current.paragraphs.length === 0 && (
                  <div className="px-4 py-8 text-center text-slate-400">{copy.noTextContent}</div>
                )}
              </div>
            </div>
          )}

          {/* Page summary pills */}
          {pageResults.length > 1 && (
            <div className="bg-white border border-gray-200 rounded-xl p-4 mt-4">
              <h3 className="font-bold text-slate-900 text-sm mb-3">{copy.pageSummary}</h3>
              <div className="flex flex-wrap gap-2">
                {pageResults.map((page, index) => {
                  const changes = page.addedWords + page.removedWords
                  return (
                    <button
                      key={index}
                      onClick={() => setCurrentPage(index)}
                      className={cn(
                        "text-xs font-medium px-3 py-1.5 rounded-lg border transition-colors",
                        currentPage === index && "ring-2 ring-indigo-500",
                        changes === 0 && "bg-green-50 border-green-200 text-green-700",
                        changes > 0 && changes <= 20 && "bg-yellow-50 border-yellow-200 text-yellow-700",
                        changes > 20 && changes <= 80 && "bg-[#F0FDFA] border-[#14D8C4]/20 text-[#0FBFB0]",
                        changes > 80 && "bg-red-50 border-red-200 text-red-700"
                      )}
                    >
                      P{index + 1}: {changes === 0 ? copy.same : `${changes} ${changes === 1 ? copy.word : copy.words}`}
                    </button>
                  )
                })}
              </div>
            </div>
          )}
        </div>
      </div>
    </section>
  )
}
